# Generated by Django 3.1.1 on 2020-10-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='timeStamp',
        ),
    ]
